{{- if .Values.service.enable}}
appVersion: v1
kind: service
metadata:
  name: {{.Release.Name}}-{{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}} ## Porta que o serviço roda
      targetPort: {{.Values.containerPorts.http}} ## Porta onde o container escuta
{{- end }}